service:
  name: login
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  testRoute:
    handler: handler.test
    events:
      - http:
          method: get
          path: test
  loginPostRoute:
    handler: loginhandler.login
    events: 
      - http:
          method: get
          path: user/login
      - http:
          method: post
          path: user/login